language: python

sudo: false

python:
  - "3.5"

install:
 - npm install
 - pip install -r requirements.txt

before_script:
 - npm run release

script:
 - scripts/runtests

notifications:
  slack:
    secure: nI5w7rd891UDo/+66igQKfM5+r0zYXoRM5WQrRtJpbn158rIMbkqY3XGaSQIEwKa4owgypczdNrZsWdXFadW0CP6Mpm48Lzgki0J07SyZsgQ+MaUvIjLcIYVrolofffSzFky/wYC/QbwsBo5ovGvmJEO33e/jvGES5V4HKVuJDhFtuaROeCgofaC3zJhdOc2lrodm2pZg2gw8MmI1E6YS1bpR2QPxCt4bPOUJhxUI5wnvQllYQr09wFewtG/DT7QOtupLkanY6N2NZOHTb6wpa033AIn+Y/WczvK+QJ17X9kJgJxDEjz55voTjWribqkInT3v6wizamJy8giJVL6LGFjuBGPHzOEVQz7CigrhT5sQQGNl5xC1GzIildMrv6Koxc2rA/+VhZGHbaZ6Be/xGK0Z9TngnahBVmCdLG1ZwKCt16amtwoQRlDyIGqUuUtbjwR4+v3GX2OStiupIyEXvVIiVAY/3rwnqxwe/02X6f0SEk2lxkHymZijFRI58gDD1cPrkiT61BiPk3YtgA0JYCDWUcuL56YyOekB110r7+9uVLRAn6EGpYWUB5hkjwJe0+Rw/BtNE4VmgoX3x+fdOVlQMWHifBnlylEi7h0cRHqHq4ejElHJyMUC9Zgvdi/uSrRJneQcDfbiXSZsiZv3l9PsQirICJR42re5UPlfA0=
